version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Le conteneur Nginx Ã©coute sur le port 80
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - ENDPOINT_URL=${ENDPOINT_URL}
      - AGENT_URL=${AGENT_URL}
    depends_on:
      - ai-agent
      - endpoint

  ai-agent:
    build: ./ai-agent
    ports:
      - "5000:5000"

  endpoint:
    build: ./endpoint
    ports:
      - "8890:8890"  # Port du SPARQL endpoint Virtuoso
      - "1111:1111"  # Port pour isql (administration)
